name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
      with:
        source_file: 'MLModels/SentimentModel.zip'
        destination_repo: 'PradeepLoganathan/ModelRepository'
        destination_folder: 'SentimentAnalysis'
        user_email: 'pradeep@email.com'
        user_name: 'pradeeploganathan'
        commit_message: 'A custom message for the commit'