name: Copy Files

on:
  push:
    branches: [ main ]

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push generated file to another repository
        uses: nkoppel/push-files-to-another-repository@1.1.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          source-files: 'MLModels/SentimentModel.zip'
          destination-username: 'PradeepLoganathan'
          destination-repository: 'ModelRepository'
          destination-directory: 'SentimentAnalysis'
          commit-email: 'pradeep@gmail.com'